# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IDS(object):
    def setupUi(self, IDS):
        IDS.setObjectName("IDS")
        IDS.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(IDS)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.layoutnodo = QtWidgets.QWidget()
        self.layoutnodo.setGeometry(QtCore.QRect(0, 0, 516, 580))
        self.layoutnodo.setObjectName("layoutnodo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutnodo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.layoutnodo)
        self.horizontalLayout.addWidget(self.scrollArea)
        IDS.setCentralWidget(self.centralwidget)

        self.retranslateUi(IDS)
        QtCore.QMetaObject.connectSlotsByName(IDS)

    def retranslateUi(self, IDS):
        _translate = QtCore.QCoreApplication.translate
        IDS.setWindowTitle(_translate("IDS", "IDS"))
        self.treeWidget.headerItem().setText(0, _translate("IDS", "Proyecto"))
        self.pushButton.setText(_translate("IDS", "Guardar PDF"))
