# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\nodo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 330)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("border: 1px solid black; border-radius: 5px; padding: 2px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.color = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color.sizePolicy().hasHeightForWidth())
        self.color.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.color.setFont(font)
        self.color.setStyleSheet("border: 1px solid black; border-radius: 5px; padding: 2px;\n"
"background-color: rgb(255, 255, 255);")
        self.color.setDefault(False)
        self.color.setFlat(False)
        self.color.setObjectName("color")
        self.horizontalLayout_2.addWidget(self.color)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget_nodos = QtWidgets.QWidget(Form)
        self.widget_nodos.setEnabled(True)
        self.widget_nodos.setStyleSheet("border: 1px solid black; ")
        self.widget_nodos.setObjectName("widget_nodos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_nodos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nodos = QtWidgets.QGridLayout()
        self.nodos.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.nodos.setContentsMargins(1, 1, 1, 1)
        self.nodos.setObjectName("nodos")
        self.fvgnvbghm = QtWidgets.QWidget(self.widget_nodos)
        self.fvgnvbghm.setStyleSheet("border: 0px solid black; ")
        self.fvgnvbghm.setObjectName("fvgnvbghm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fvgnvbghm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.Spin = QtWidgets.QDoubleSpinBox(self.fvgnvbghm)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Spin.setFont(font)
        self.Spin.setStyleSheet("border: 1px solid black; border-radius: 5px; padding: 2px;\n"
"background-color: rgb(255, 255, 255);")
        self.Spin.setObjectName("Spin")
        self.gridLayout_2.addWidget(self.Spin, 0, 1, 1, 1)
        self.nodos.addWidget(self.fvgnvbghm, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.nodos)
        self.verticalLayout.addWidget(self.widget_nodos)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setStyleSheet("border: 1px solid black; border-radius: 5px; padding: 2px;\n"
"background-color: rgb(255, 255, 255);")
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.delete_2 = QtWidgets.QPushButton(Form)
        self.delete_2.setStyleSheet("border: 1px solid black; border-radius: 5px; padding: 2px;\n"
"background-color: rgb(255, 255, 255);")
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout.addWidget(self.delete_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.color.setText(_translate("Form", "Color"))
        self.add.setText(_translate("Form", "Añadir nuevo nodo"))
        self.delete_2.setText(_translate("Form", "Eliminar nodo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
